async function exportToDOCX(htmlContent, customFilename) {
    const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, ImageRun } = window.docx;

    const tempDiv = document.createElement('div');
    tempDiv.innerHTML = htmlContent;

    const docChildren = [
        new Paragraph({
            text: customFilename || "Study Notes",
            heading: HeadingLevel.HEADING_1,
            alignment: AlignmentType.CENTER,
            spacing: { after: 200 }
        }),
        new Paragraph({
            children: [
                new TextRun({
                    text: `Generated on: ${new Date().toLocaleString()}`,
                    italics: true,
                    color: "636E72",
                })
            ],
            alignment: AlignmentType.CENTER,
            spacing: { after: 400 }
        })
    ];

    function base64ToUint8Array(base64) {
        const binaryString = atob(base64.split(',')[1]);
        const len = binaryString.length;
        const bytes = new Uint8Array(len);
        for (let i = 0; i < len; i++) {
            bytes[i] = binaryString.charCodeAt(i);
        }
        return bytes;
    }

    function parseNode(node, currentStyles = {}) {
        if (node.nodeType === 3) { // Text node
            const text = node.textContent;
            if (!text.trim() && text !== ' ' && text !== '\n') return [];
            return [new TextRun({ text: text, ...currentStyles })];
        }

        if (node.nodeType !== 1) return [];

        const tagName = node.tagName.toLowerCase();
        
        const newStyles = { ...currentStyles };
        if (tagName === 'b' || tagName === 'strong') newStyles.bold = true;
        if (tagName === 'i' || tagName === 'em') newStyles.italics = true;
        if (tagName === 'u') newStyles.underline = {};
        if (tagName === 'font' && node.getAttribute('face') === 'monospace') newStyles.font = "Courier New";

        const runs = [];
        node.childNodes.forEach(child => {
            if (child.nodeType === 1 && child.tagName.toLowerCase() === 'br') {
                // In docx.js, newlines are often better handled as separate paragraphs
                // but inside a text run parser, we can't easily break the paragraph.
                // However, our top-level loop handles block breaks.
                runs.push(new TextRun({ break: 1 }));
            } else {
                runs.push(...parseNode(child, newStyles));
            }
        });
        return runs;
    }

    tempDiv.childNodes.forEach(node => {
        if (node.nodeType !== 1) return;
        const tagName = node.tagName.toLowerCase();
        const alignment = node.style.textAlign?.toUpperCase() || AlignmentType.LEFT;
        
        if (tagName === 'h4') {
            docChildren.push(new Paragraph({ text: node.innerText, heading: HeadingLevel.HEADING_4, alignment: AlignmentType[alignment] || AlignmentType.LEFT }));
        } else if (tagName === 'pre') {
            // Aggressive line-break detection: convert block starts and br tags to newlines
            let rawText = node.innerHTML
                .replace(/<br\s*\/?>/gi, '\n')
                .replace(/<(div|p|li)[^>]*>/gi, '\n')
                .replace(/<[^>]+>/g, ''); 
            
            const decoder = document.createElement('textarea');
            decoder.innerHTML = rawText;
            rawText = decoder.value;

            rawText.split('\n').forEach(line => {
                // Skip completely empty lines generated by tag pairs, but keep intended spacing
                if (line.trim() === '' && line.length === 0) return;
                
                docChildren.push(new Paragraph({
                    children: [new TextRun({ text: line, font: "Courier New", size: 20 })],
                    spacing: { before: 0, after: 0 },
                    alignment: AlignmentType.LEFT
                }));
            });
        } else if (tagName === 'img' || node.querySelector('img')) {
            const img = tagName === 'img' ? node : node.querySelector('img');
            const src = img.getAttribute('src');
            if (src && src.startsWith('data:image')) {
                docChildren.push(new Paragraph({
                    children: [new ImageRun({
                        data: base64ToUint8Array(src),
                        transformation: { width: 400, height: 300 },
                    })],
                    alignment: AlignmentType.CENTER,
                    spacing: { before: 200, after: 200 }
                }));
            }
        } else if (tagName === 'ul' || tagName === 'ol') {
            node.childNodes.forEach(li => {
                if (li.nodeType === 1 && li.tagName.toLowerCase() === 'li') {
                    docChildren.push(new Paragraph({ children: parseNode(li), bullet: tagName === 'ul' ? { level: 0 } : undefined }));
                }
            });
        } else if (node.innerText?.trim() || node.querySelector('img')) {
            docChildren.push(new Paragraph({ 
                children: parseNode(node),
                alignment: AlignmentType[alignment] || AlignmentType.LEFT 
            }));
        }
    });

    const doc = new Document({ sections: [{ properties: {}, children: docChildren }] });
    const blob = await Packer.toBlob(doc);
    let filename = customFilename ? (customFilename.endsWith('.docx') ? customFilename : `${customFilename}.docx`) : `StudyNotes_${new Date().toISOString().slice(0, 10)}.docx`;
    saveAs(blob, filename);
}
